### ISSUE TITLE
Test files are missing lib/all-min.js

### ISSUE THREAD

**Issue by mikechambers** [beastaugh/firmin#19]
None of the test files will run as they are trying to load the:

lib/all-min.js

file, which is not included in the repository.

**Comment by beastaugh** [comment]
Yeah, you need to install [Jake](https://github.com/jcoglan/jake), which is a build tool written in Ruby (`gem install jake` if you have Ruby and Rubygems) and then run the `jake` command in the top-level directory of your copy of the repository.

Sorry this isn't documented anywhere, I've been meaning to add some stuff about hacking on Firmin to the README but just haven't quite got round to it yet.

**Comment by beastaugh** [comment]
I've just added some brief build instructions to the README. Let me know if they're unclear.
